# Generated by Django 5.2.7 on 2026-02-24 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='input_type',
        ),
    ]
