# Generated by Django 5.2.7 on 2025-10-31 15:29
import django
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='subcategories',
                blank=True,
                null=True,
                to='marketplace.category',
            ),
        ),
    ]

