# Generated by Django 5.2.7 on 2025-11-30 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='items/thumbs/'),
        ),
    ]
