# Generated by Django 5.2.7 on 2026-02-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_remove_attribute_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='ui_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox List'), ('single_checkbox', 'Single Checkbox'), ('tags', 'Tags / Multi-Select')], default='dropdown', max_length=50, null=True),
        ),
    ]
