# Generated by Django 5.2.7 on 2025-11-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_user_points_user_referral_code_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='ui_type',
            field=models.CharField(choices=[('dropdown', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox List'), ('single_checkbox', 'Single Checkbox'), ('tags', 'Tags / Multi-Select')], default='dropdown', max_length=50),
        ),
    ]
