# Generated by Django 5.2.7 on 2026-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_attribute_ui_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='input_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='ui_type',
            field=models.CharField(blank=True, choices=[('dropdown', 'Dropdown'), ('radio', 'Radio Buttons'), ('checkbox', 'Checkbox List'), ('single_checkbox', 'Single Checkbox'), ('tags', 'Tags / Multi-Select')], max_length=50, null=True),
        ),
    ]
