# Generated by Django 5.2.7 on 2025-12-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_category_child_label_ar_category_child_label_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='child_label_ar',
            new_name='child_label',
        ),
        migrations.RemoveField(
            model_name='category',
            name='child_label_en',
        ),
    ]
