# Generated by Django 5.2.7 on 2026-02-27 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_attribute_input_type_alter_attribute_ui_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryphoto',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='marketplace.category'),
        ),
        migrations.AlterField(
            model_name='categoryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
