# Generated by Django 5.2.7 on 2025-10-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
