# Generated by Django 5.2.7 on 2025-12-26 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='IssuesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_kind', models.CharField(choices=[('listing', 'Listing'), ('user', 'User'), ('store', 'Store')], db_index=True, max_length=10)),
                ('listing_type', models.CharField(blank=True, choices=[('item', 'Item'), ('request', 'Request')], db_index=True, max_length=10, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.listing')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='IssueReport',
        ),
        migrations.AddIndex(
            model_name='issuesreport',
            index=models.Index(fields=['target_kind', 'status', 'created_at'], name='marketplace_target__1df279_idx'),
        ),
        migrations.AddIndex(
            model_name='issuesreport',
            index=models.Index(fields=['listing_type', 'status', 'created_at'], name='marketplace_listing_570ca8_idx'),
        ),
    ]
