# Generated by Django 5.2.7 on 2026-02-28 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0005_alter_categoryphoto_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marketplace.store",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
