# Generated by Django 5.2.7 on 2026-03-01 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0006_notification_add_store_fk"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_ar",
                    models.CharField(default="شروط الاستخدام", max_length=200),
                ),
                (
                    "subtitle_ar",
                    models.CharField(
                        blank=True,
                        default="ميثاقنا المشترك لضمان تجربة آمنة وموثوقة لكافة مستخدمي منصة ركن.",
                        max_length=300,
                    ),
                ),
                (
                    "sidebar_note_ar",
                    models.CharField(
                        blank=True,
                        default="باستخدامك للمنصة، أنت توافق ضمنياً على كافة البنود المذكورة هنا.",
                        help_text="النص الظاهر في مربع السايدبار.",
                        max_length=300,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_active", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="TermsSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "anchor_key",
                    models.SlugField(
                        help_text="مفتاح فريد للـ anchor في الصفحة، مثال: acceptance, account, content",
                        max_length=60,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        default="file-text",
                        help_text="اسم أيقونة Lucide، مثال: check-circle, user-check, file-warning",
                        max_length=40,
                    ),
                ),
                ("title_ar", models.CharField(max_length=200)),
                (
                    "body_ar",
                    models.TextField(
                        help_text="النص الرئيسي للقسم (يمكن استخدام أسطر جديدة)."
                    ),
                ),
                (
                    "warning_ar",
                    models.TextField(
                        blank=True,
                        help_text="نص تحذير اختياري يظهر في مربع برتقالي أسفل النص (مثال: قسم إخلاء المسؤولية).",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="marketplace.termspage",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
    ]
