# Generated by Django 5.2.7 on 2025-12-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_user_username_issuesreport_delete_issuereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesreport',
            name='reason',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
