# Generated by Django 5.2.7 on 2025-10-26 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_item_condition_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.item'),
        ),
    ]
