# Generated by Django 5.2.7 on 2025-11-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_item_approved_at_item_approved_by_item_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemphoto',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
