# Generated by Django 5.2.7 on 2026-03-01 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0007_terms_page"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privacypolicysection",
            old_name="heading_ar",
            new_name="title_ar",
        ),
        migrations.AddField(
            model_name="privacypolicypage",
            name="cta_button_ar",
            field=models.CharField(
                blank=True, default="تواصل مع الدعم الفني", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="privacypolicypage",
            name="cta_subtitle_ar",
            field=models.CharField(
                blank=True,
                default="إذا كان لديك أي سؤال حول سياسة الخصوصية، فريق الدعم لدينا جاهز لمساعدتك.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="privacypolicypage",
            name="cta_title_ar",
            field=models.CharField(
                blank=True, default="هل لديك استفسار؟", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="privacypolicypage",
            name="cta_url",
            field=models.CharField(blank=True, default="#", max_length=200),
        ),
        migrations.AddField(
            model_name="privacypolicypage",
            name="sidebar_note_ar",
            field=models.CharField(
                blank=True,
                default="بياناتك في أمان. نلتزم بسرية معلوماتك ولن نشاركها مع أي طرف ثالث.",
                help_text="النص الظاهر في مربع السايدبار.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="privacypolicysection",
            name="anchor_key",
            field=models.SlugField(
                blank=True,
                help_text="مفتاح فريد للـ anchor في الصفحة، مثال: collection, usage, rights",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="privacypolicysection",
            name="icon",
            field=models.CharField(
                blank=True,
                default="info",
                help_text="اسم أيقونة Lucide، مثال: shield, lock, eye",
                max_length=40,
            ),
        ),
    ]
