# Generated by Django 5.2.7 on 2025-12-26 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_user_date_joined_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='store',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
