# Generated by Django 5.2.7 on 2026-03-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0008_privacy_policy_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_points",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Points awarded to every new user upon registration.",
                    ),
                ),
                (
                    "referral_points",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="Points awarded to the referrer when an invited friend registers.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
