# Generated by Django 5.2.7 on 2025-10-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_city_item_updated_at_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sold_on_site',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
