# Generated by Django 5.2.7 on 2025-12-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_remove_store_phone_alter_store_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
