# Generated by Django 5.2.7 on 2025-12-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_store_rating_avg_store_rating_count_storereview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='show_phone',
        ),
        migrations.AddField(
            model_name='listing',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
    ]
