# Generated by Django 5.2.7 on 2026-03-10 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0011_lost_found"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoundReport",
            fields=[],
            options={
                "verbose_name": "Found Report",
                "verbose_name_plural": "Found Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("marketplace.report",),
        ),
        migrations.CreateModel(
            name="LostReport",
            fields=[],
            options={
                "verbose_name": "Lost Report",
                "verbose_name_plural": "Lost Reports",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("marketplace.report",),
        ),
    ]
