# Generated by Django 5.2.7 on 2025-10-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_phone',
            field=models.BooleanField(default=True, help_text='If true, your phone number will be visible to other users.'),
        ),
    ]
