# Generated by Django 5.2.7 on 2026-03-10 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0012_lost_found_proxy_models"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="conversation",
            name="conversation_exactly_one_target",
        ),
        migrations.AddField(
            model_name="conversation",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="marketplace.report",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("listing__isnull", False),
                        ("store__isnull", True),
                        ("report__isnull", True),
                    ),
                    models.Q(
                        ("listing__isnull", True),
                        ("store__isnull", False),
                        ("report__isnull", True),
                    ),
                    models.Q(
                        ("listing__isnull", True),
                        ("store__isnull", True),
                        ("report__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="conversation_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("report__isnull", False)),
                fields=("report", "buyer", "seller"),
                name="uniq_convo_report_buyer_seller",
            ),
        ),
    ]
