# Generated by Django 5.2.7 on 2026-01-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_remove_request_show_phone_listing_show_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesreport',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
