# Generated by Django 5.2.7 on 2026-01-04 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_issuesreport_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured_until',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='ListingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('featured', 'Featured')], default='featured', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('points_cost', models.PositiveIntegerField(default=0)),
                ('paid_with_points', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='marketplace.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_promotions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('spend', 'Spend'), ('earn', 'Earn'), ('adjust', 'Adjust')], max_length=20)),
                ('delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reason', models.CharField(blank=True, default='', max_length=80)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='marketplace.listingpromotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=40)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='marketplace.listingpromotion')),
            ],
        ),
        migrations.AddIndex(
            model_name='listingpromotion',
            index=models.Index(fields=['kind', 'status', 'ends_at'], name='marketplace_kind_e635e6_idx'),
        ),
        migrations.AddIndex(
            model_name='listingpromotion',
            index=models.Index(fields=['listing', 'kind'], name='marketplace_listing_ed33e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='listingpromotion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ends_at__isnull', True), ('starts_at__isnull', True)), ('ends_at__gt', models.F('starts_at')), _connector='OR'), name='promo_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='listingpromotion',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('listing', 'kind'), name='uniq_active_promo_per_listing_kind'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['user', 'created_at'], name='marketplace_user_id_596801_idx'),
        ),
        migrations.AddIndex(
            model_name='promotionevent',
            index=models.Index(fields=['event', 'created_at'], name='marketplace_event_7f6bbe_idx'),
        ),
    ]
