# Generated by Django 5.2.7 on 2026-01-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_listing_featured_until_listingpromotion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemphoto',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='itemphoto',
            name='normalized',
            field=models.ImageField(blank=True, null=True, upload_to='items/normalized/'),
        ),
    ]
