# Generated by Django 5.2.7 on 2026-01-08 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_remove_itemphoto_thumbnail_itemphoto_normalized'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storereview',
            name='subject',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_active', 'created_at'], name='marketplace_is_acti_402827_idx'),
        ),
        migrations.AddIndex(
            model_name='storereview',
            index=models.Index(fields=['store', '-created_at'], name='marketplace_store_i_ef0507_idx'),
        ),
        migrations.AddIndex(
            model_name='storereview',
            index=models.Index(fields=['reviewer', '-created_at'], name='marketplace_reviewe_dfc036_idx'),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='marketplace.store'),
        ),
        migrations.AddField(
            model_name='storefollow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_stores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='storefollow',
            index=models.Index(fields=['store', 'user'], name='marketplace_store_i_7dd19d_idx'),
        ),
        migrations.AddIndex(
            model_name='storefollow',
            index=models.Index(fields=['user', 'created_at'], name='marketplace_user_id_a8aafd_idx'),
        ),
        migrations.AddConstraint(
            model_name='storefollow',
            constraint=models.UniqueConstraint(fields=('store', 'user'), name='uniq_store_follow'),
        ),
    ]
