# Generated by Django 5.2.7 on 2026-01-09 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_storefollow_store_is_featured_store_views_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplace.store'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='marketplace.listing'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('listing__isnull', False), ('store__isnull', True)), models.Q(('listing__isnull', True), ('store__isnull', False)), _connector='OR'), name='conversation_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('listing__isnull', False)), fields=('listing', 'buyer', 'seller'), name='uniq_convo_listing_buyer_seller'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('store__isnull', False)), fields=('store', 'buyer', 'seller'), name='uniq_convo_store_buyer_seller'),
        ),
    ]
