# Generated by Django 5.2.7 on 2026-01-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0017_conversation_store_alter_conversation_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='followers_notified',
            field=models.BooleanField(default=False),
        ),
    ]
