# Generated by Django 5.2.7 on 2026-01-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0019_store_address_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_policy',
            field=models.CharField(blank=True, choices=[('24', 'خلال 24 ساعة'), ('48', 'خلال 48 ساعة'), ('72', 'خلال 72 ساعة')], max_length=2),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='store',
            name='return_policy',
            field=models.CharField(blank=True, choices=[('3', 'خلال 3 أيام'), ('7', 'خلال 7 أيام'), ('none', 'لا يوجد إرجاع')], max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
