# Generated by Django 5.2.7 on 2026-01-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0020_store_delivery_policy_store_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('system', 'System'), ('listing', 'Listing'), ('message', 'Message'), ('request', 'Request'), ('wallet', 'Wallet')], default='system', max_length=30),
        ),
    ]
