# Generated by Django 5.2.7 on 2026-01-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0021_notification_kind'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='kind',
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('system', 'System'), ('listing', 'Listing'), ('request', 'Request'), ('message', 'Message'), ('wallet', 'Wallet'), ('alert', 'Alert')], default='system', max_length=20),
        ),
    ]
