# Generated by Django 5.2.7 on 2026-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0022_remove_notification_kind_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(db_index=True, default='general', max_length=50),
        ),
    ]
