# Generated by Django 5.2.7 on 2026-01-20 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0023_alter_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(db_index=True, default='system', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketplace.listing'),
        ),
    ]
