# Generated by Django 5.2.7 on 2026-01-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_remove_notification_type_notification_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
