# Generated by Django 5.2.7 on 2026-02-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0025_listing_deleted_at_listing_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('subject', models.CharField(choices=[('account', 'مشكلة حساب'), ('suggestion', 'اقتراح'), ('complaint', 'شكوى'), ('other', 'أخرى')], max_length=20)),
                ('contact_method', models.CharField(choices=[('phone', 'رقم الهاتف'), ('email', 'البريد الإلكتروني')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
        ),
    ]
