# Generated by Django 5.2.7 on 2026-02-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Unique key used in template anchors. Example: about, account, ads...', max_length=32, unique=True)),
                ('name_ar', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, default='circle-help', help_text='Lucide icon name, e.g. info, user-cog, megaphone...', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ar', models.CharField(max_length=255)),
                ('answer_ar', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='marketplace.faqcategory')),
            ],
            options={
                'ordering': ['category__order', 'order', 'id'],
            },
        ),
    ]
