# Generated by Django 5.2.7 on 2026-02-01 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0027_faqcategory_faqquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(default='سياسة الخصوصية', max_length=200)),
                ('subtitle_ar', models.CharField(blank=True, default='نوضح هنا كيف نجمع بياناتك ونستخدمها ونحميها داخل منصة ركن.', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('heading_ar', models.CharField(max_length=200)),
                ('body_ar', models.TextField(help_text='اكتب النص العربي (يمكنك استخدام أسطر جديدة).')),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='marketplace.privacypolicypage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
