# Generated by Django 5.2.7 on 2026-02-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0028_privacypolicypage_privacypolicysection'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
