# Generated by Django 5.2.7 on 2026-02-04 22:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0029_listing_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='published_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
