# Generated by Django 5.2.7 on 2026-02-07 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0030_listing_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='marketplace.category')),
            ],
        ),
    ]
