# Generated by Django 5.2.7 on 2026-02-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0031_categoryphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='condition_preference',
            field=models.CharField(choices=[('any', 'لا يهم'), ('new', 'جديد'), ('used', 'مستعمل')], default='any', max_length=10),
        ),
    ]
