# Generated by Django 5.2.7 on 2026-02-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0032_alter_request_condition_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuesreport',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20),
        ),
    ]
