# Generated by Django 5.2.7 on 2026-02-22 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0033_alter_issuesreport_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuesreport',
            name='action_taken',
            field=models.TextField(blank=True, help_text='Describe the action taken by the admin when resolving or dismissing this report.', null=True),
        ),
        migrations.AddField(
            model_name='issuesreport',
            name='actioned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuesreport',
            name='actioned_by',
            field=models.ForeignKey(blank=True, help_text='The admin who resolved or dismissed this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
