# Generated by Django 5.2.7 on 2026-02-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0034_issuesreport_action_taken_issuesreport_actioned_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='subtitle_ar',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='category',
            name='child_label',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='category',
            name='subtitle_en',
        ),
    ]
