# Generated by Django 5.2.7 on 2026-02-23 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0035_remove_bilingual_category_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='attributeoption',
            old_name='value_ar',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='attributeoption',
            name='value_en',
        ),
    ]
